name: Firebase Production Deployment

# Deploy to production when:
# 1. Code is pushed to main branch
# 2. A release tag is created
# 3. Manually triggered via workflow_dispatch
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Matches v1.0.0, v2.1.3, etc.

  workflow_dispatch:
    inputs:
      skip-tests:
        description: 'Skip tests (not recommended)'
        required: false
        default: 'false'

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ secrets.FIREBASE_PROJECT_ID }}.web.app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
        continue-on-error: false

      - name: Run tests
        if: github.event.inputs.skip-tests != 'true'
        run: npm test
        continue-on-error: false

      - name: Build for production
        run: npm run build
        env:
          VITE_ENV: production
          VITE_API_URL: ${{ secrets.PROD_API_URL }}
          VITE_FIREBASE_API_KEY: ${{ secrets.PROD_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.PROD_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Create deployment summary
        run: |
          echo "## 🚀 Production Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Project:** ${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_STEP_SUMMARY
          echo "**URL:** https://${{ secrets.FIREBASE_PROJECT_ID }}.web.app" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered by:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Post-Deployment Checklist" >> $GITHUB_STEP_SUMMARY
          echo "- [ ] Verify site loads" >> $GITHUB_STEP_SUMMARY
          echo "- [ ] Check authentication" >> $GITHUB_STEP_SUMMARY
          echo "- [ ] Test critical user flows" >> $GITHUB_STEP_SUMMARY
          echo "- [ ] Monitor error logs" >> $GITHUB_STEP_SUMMARY
          echo "- [ ] Check analytics" >> $GITHUB_STEP_SUMMARY

      - name: Notify deployment success
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // You can add Slack/Discord webhook notification here
            console.log('Production deployment successful!');

      - name: Notify deployment failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // You can add Slack/Discord webhook notification here
            console.error('Production deployment failed!');
