name: Firebase Production Deployment

# Deploy to production when:
# 1. Code is pushed to main branch (affecting coffee-website-react)
# 2. Manually triggered via workflow_dispatch
on:
  push:
    branches:
      - main
    paths:
      - 'coffee-website-react/**'
      - '.github/workflows/firebase-production.yml'

  workflow_dispatch:
    inputs:
      skip-build:
        description: 'Skip build step (not recommended)'
        required: false
        default: 'false'

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: coffee-website-react
        run: npm install

      - name: Run linter
        working-directory: coffee-website-react
        run: npm run lint -- --ignore-pattern 'scripts/**' --ignore-pattern '*.config.ts'
        continue-on-error: true

      - name: Build for production
        if: github.event.inputs.skip-build != 'true'
        working-directory: coffee-website-react
        run: npm run build
        env:
          VITE_ENV: production
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}
          VITE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          VITE_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          VITE_COPILOT_API_URL: ${{ secrets.VITE_COPILOT_API_URL }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: deploy
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live
          entryPoint: coffee-website-react
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Create deployment summary
        run: |
          echo "## 🚀 Production Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Project:** ${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_STEP_SUMMARY
          echo "**URL:** https://${{ secrets.FIREBASE_PROJECT_ID }}.web.app" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered by:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Post-Deployment Checklist" >> $GITHUB_STEP_SUMMARY
          echo "- [ ] Verify site loads at https://${{ secrets.FIREBASE_PROJECT_ID }}.web.app" >> $GITHUB_STEP_SUMMARY
          echo "- [ ] Check authentication flows" >> $GITHUB_STEP_SUMMARY
          echo "- [ ] Test shopping cart and checkout" >> $GITHUB_STEP_SUMMARY
          echo "- [ ] Verify Stripe payments work" >> $GITHUB_STEP_SUMMARY
          echo "- [ ] Check product inventory loads" >> $GITHUB_STEP_SUMMARY
          echo "- [ ] Monitor error logs in Firebase Console" >> $GITHUB_STEP_SUMMARY
          echo "- [ ] Test on mobile devices" >> $GITHUB_STEP_SUMMARY

      - name: Notify deployment success
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('✅ Production deployment successful!');
            console.log('URL: https://${{ secrets.FIREBASE_PROJECT_ID }}.web.app');

      - name: Notify deployment failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.error('❌ Production deployment failed!');
            core.setFailed('Deployment to production failed. Check the logs for details.');
